<a href="https://colab.research.google.com/github/KDS-Creator/PHY3638_Machine_Learning/blob/main/Lab1/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Library
import numpy as np

# Common Attribute

In [2]:
data = np.array([7, 2, 9, 10])

print(data)
print(data.shape)
print(data.size)
print(data.dtype)
print(data.nbytes)
print(data.ndim)

[ 7  2  9 10]
(4,)
4
int64
32
1


In [3]:
data = np.array([[5.2, 3.0, 4.5],
                 [9.1, 0.1, 0.3]])

print(data)
print(data.shape)
print(data.ndim)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
2


In [4]:
data = np.array([1, 2, 3])

print(data.dtype)

int64


In [5]:
data = np.array([1, 2, 3], dtype=np.float64)

In [6]:
print(data.dtype)

float64


# Update an element

In [7]:
data = np.array([1, 2, 3])
print(data)
data[0] = 8
print(data)

[1 2 3]
[8 2 3]


# Create numpy array

In [9]:
my_list = [8, 7, 6, 9]
my_array = np.array(my_list)
print(my_array)

[8 7 6 9]


In [10]:
# Common functions
# zeros()
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
# ones()
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# full()
arr = np.full((2, 3), 8)
print(arr)

[[8 8 8]
 [8 8 8]]


In [13]:
# arange()
arr1 = np.arange(5)
print(arr1)
arr2 = np.arange(0, 11, 5)
print(arr2)

[0 1 2 3 4]
[ 0  5 10]


In [14]:
# eye()
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# random()
arr = np.random.random((2, 3))
print(arr)

[[0.28849674 0.75881428 0.79038545]
 [0.18733729 0.80928914 0.85599811]]


In [16]:
# numpy.hstack()
arr1 = np.array([0, 1, 2, 3])
print("arr1: ", arr1)

arr2 = np.array([4, 5, 6, 7])
print("arr2: ", arr2)

result = np.hstack((arr1, arr2))
print('result: ', result)

arr1:  [0 1 2 3]
arr2:  [4 5 6 7]
result:  [0 1 2 3 4 5 6 7]


In [18]:
# numpy.vstack()
arr1 = np.array([0, 1, 2, 3])
print("arr1: ", arr1)

arr2 = np.array([4, 5, 6, 7])
print("arr2: ", arr2)

result = np.vstack((arr1, arr2))
print('result: \n', result)

arr1:  [0 1 2 3]
arr2:  [4 5 6 7]
result: 
 [[0 1 2 3]
 [4 5 6 7]]


In [20]:
# numpy.concatenate()
arr1 = np.array([[0, 1, 2, 3]])
print("arr1: ", arr1)

arr2 = np.array([[4, 5, 6, 7]])
print("arr2: ", arr2)

result1 = np.concatenate((arr1, arr2), axis=0)
print("result1: \n", result1)

result2 = np.concatenate((arr1, arr2), axis=1)
print("result2: \n", result2)

arr1:  [[0 1 2 3]]
arr2:  [[4 5 6 7]]
result1: 
 [[0 1 2 3]
 [4 5 6 7]]
result2: 
 [[0 1 2 3 4 5 6 7]]


In [21]:
# numpy.array_split
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [22]:
# where() function
arr = np.array([[0, 1, 2, 3]])
condition = arr < 2
print(condition)

out = np.where(condition, arr, arr**2)
print(out)

[[ True  True False False]]
[[0 1 4 9]]


In [23]:
# flatten
arr = np.array([[0, 1],
                [4, 5]])
out = arr.flatten()
print(arr)
print(out)

[[0 1]
 [4 5]]
[0 1 4 5]


In [25]:
# reshape
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7]])

print(arr)
print("Shape: ", arr.shape)

out = np.reshape(arr, (4, 2))
print(out)
print("shape: ", out.shape)

[[0 1 2 3]
 [4 5 6 7]]
Shape:  (2, 4)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
shape:  (4, 2)


# Array Indexing

In [27]:
arr = np.array([[0, 1],
               [2, 3],
               [4, 5],
               [6, 7]])

print(arr)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [28]:
arr[0, 1]

1

In [29]:
arr[1:3]

array([[2, 3],
       [4, 5]])

In [30]:
print(arr[0:2, 0])

[0 2]


In [31]:
print(arr[:, 1:])

[[1]
 [3]
 [5]
 [7]]


In [32]:
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11],
                [12, 13, 14, 15]])

print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [33]:
print(arr[0, :])

[0 1 2 3]


In [34]:
print(arr[1, :])

[4 5 6 7]


In [36]:
print(arr[:, 2:3])

[[ 2]
 [ 6]
 [10]
 [14]]


In [37]:
print(arr[0:2, 0:2])

[[0 1]
 [4 5]]


In [39]:
print(arr[0:2, 2:])

[[2 3]
 [6 7]]


In [42]:
print(arr[0:3:2, 0:3:2])

[[ 0  2]
 [ 8 10]]


In [43]:
print(arr[1::2, 1::2])

[[ 5  7]
 [13 15]]


In [44]:
print(arr[:, 0::3])

[[ 0  3]
 [ 4  7]
 [ 8 11]
 [12 15]]


In [45]:
print(arr[[1, 3], [0, 3]])

[ 4 15]


In [46]:
print(arr[:, [1, 2]])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [49]:
print(arr[1:3, 1:3])

[[ 5  6]
 [ 9 10]]


# Numpy Array Operation

In [50]:
arr1 = np.array([[0, 1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7]])

out = np.add(arr1, arr2)
print('result1:\n', out)

result1:
 [[ 4  6  8 10]]


In [51]:
arr1 = np.array([[4, 5, 3, 0]])
arr2 = np.array([[0, 1, 2, 3]])

out = np.subtract(arr1, arr2)
print("result1: \n", out)

result1: 
 [[ 4  4  1 -3]]


In [52]:
arr1 = np.array([[0, 1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7]])

out = np.multiply(arr1, arr2)
print("result1: \n", out)

result1: 
 [[ 0  5 12 21]]


In [54]:
arr1 = np.array([[4, 5, 3, 1]])
arr2 = np.array([[1, 1, 2, 3]])

out = np.divide(arr1, arr2)
print("result1:\n", out)

result1:
 [[4.         5.         1.5        0.33333333]]


In [55]:
# Matrix Multiplication
X = np.array([[1, 1, 2],
              [1, 2, 3]])
Y = np.array([[0, 1],
              [2, 3],
              [4, 5]])
out = np.dot(X, Y)
print(out)
print("Shape: ", out.shape)

[[10 14]
 [16 22]]
Shape:  (2, 2)


In [56]:
# Transpose
arr = np.array([[10, 14], [16, 22]])
print(arr.T)
print(np.transpose(arr))

[[10 16]
 [14 22]]
[[10 16]
 [14 22]]
